### ISSUE TITLE
Report errors when training

### ISSUE THREAD

**Issue by jijun-cheng** [jlcsilva/EfficientUNetPlusPlus#3]
Hello!

Thanks for your work!
But I encountered some difficulties when I run `python train.py -d DRIVE -enc timm-efficientnet-b0`：

Could you tell me what the problem is and how can I solve this problem?  Thank you!
Best Wishes！
```
(EfficientUNetPP) ch@Z390-UD:~/workspace//EfficientUNetPlusPlus$ python train.py -d DRIVE -enc timm-efficientnet-b0
INFO: Using device cpu
Traceback (most recent call last):
  File "train.py", line 168, in <module>
    net = smp.EfficientUnetPlusPlus(encoder_name=args.encoder, encoder_weights="imagenet", in_channels=3, classes=n_classes)
  File "/home/cheng/workspace/EfficientUNetPlusPlus/segmentation_models_pytorch/segmentation_models_pytorch/efficientunetplusplus/model.py", line 66, in __init__
    weights=encoder_weights,
  File "/home/cheng/workspace/EfficientUNetPlusPlus/segmentation_models_pytorch/segmentation_models_pytorch/encoders/__init__.py", line 48, in get_encoder
    encoder = Encoder(**params)
  File "/home/cheng/workspace/EfficientUNetPlusPlus/segmentation_models_pytorch/segmentation_models_pytorch/encoders/timm_efficientnet.py", line 134, in __init__
    super().__init__(stage_idxs, out_channels, depth, **kwargs)
  File "/home/cheng/workspace/EfficientUNetPlusPlus/segmentation_models_pytorch/segmentation_models_pytorch/encoders/timm_efficientnet.py", line 95, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'channel_multiplier'
```

**Comment by 17SIM** [comment]
@jijun-cheng I had the same problem. For my case, it is about PyTorch version mismatching, so I reinstall 1.7.1 PyTorch and it works just fine.
